name: Deploy HTML to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate file list in HTML
        run: |
          python3 << 'EOF'
          import os
          import re
          
          # Find all HTML files except index.html
          html_files = []
          for root, dirs, files in os.walk('.'):
              for file in files:
                  if file.endswith('.html') and file != 'index.html':
                      filepath = os.path.relpath(os.path.join(root, file), '.')
                      html_files.append(filepath)
          
          print(f"Found HTML files: {html_files}")
          
          # Read index.html
          with open('index.html', 'r') as f:
              content = f.read()
          
          # Create the JavaScript array string
          files_array = '[' + ',\n    '.join([f'"{file}"' for file in html_files]) + ']'
          
          # Replace the placeholder
          content = re.sub(
              r'window\.htmlFiles = window\.htmlFiles \|\| \[\];',
              f'window.htmlFiles = {files_array};',
              content
          )
          
          # Write back to index.html
          with open('index.html', 'w') as f:
              f.write(content)
          
          print("Updated index.html successfully!")
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
